# -*- coding: utf-8 -*-
"""gen-art_min_dalle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e88I8ehWrMbzMckIkT1cJYH4n9_GgzBb
"""

!nvidia-smi

! pip install min-dalle -q

from PIL import Image
import numpy as np
from min_dalle import MinDalle
import torch

model = MinDalle(
    models_root='./pretrained',
    dtype=torch.float32,
    device='cuda',
    is_mega=True,
    is_reusable=True
)

prompt = "Nuclear explosion mus "

with open("prompt.txt", "w") as f:
  f.write(prompt)

images = model.generate_image(
    text=prompt,
    seed=-1,
    grid_size=1,
    is_seamless=False,
    temperature=1,
    top_k=256,
    supercondition_factor=1,
    is_verbose=False
)

ext = "png"
filename = "image"
image_path = "{}.{}".format(filename, ext)
images.save(image_path)

from PIL import Image
im = Image.open(image_path)
im.show()

display(im)

